### ISSUE TITLE
IDs not found or incorrectly renamed

### ISSUE THREAD

**Issue by reneruiz** [niemasd/GameDB-GC#2]
This seems like a nifty project, thanks for creating it! 🙂 

If you need me to close and re-post on the rename script repo, I can do that. Anywho, I tried to run the script against my saves:

```
D43E0100
G4BE0800
G4ME6900
G4SE0100
GAFE0100
GALE0102
GEDE0100
GFZE0100
GGSEA400
GIKE7000
GM4E0100
GM8E0102
GMPE0101
GMSE0100
GSAE0101
GSWE6400
GZLE0100
```

Appears that `GSWE6400` is the only one ID-ed but it was ID-ed as `HARRY POTTER OCH DEN FLAMMANDE BÄGAREN`. (Sidenote: Could we get title case format instead of all caps?)

But it should actually be `Star Wars Rogue Squadron II: Rogue Leader`.

![CleanShot 2024-01-16 at 21 55 53](https://github.com/niemasd/GameDB-GC/assets/394085/008173a2-f88a-4c50-a6b0-8d510379e495)

I found another potential [source](https://www.gametdb.com/Wii/Downloads) for GameIDs, however the format doesn't quite line up nicely.

```
Title: Star Wars Rogue Squadron II: Rogue Leader
MemCardPro ID: GSWE6400
GameTDB ID: GSWE64
```

Here's the MCP mapping for all my saves with title + ID:

![CleanShot 2024-01-16 at 22 04 17](https://github.com/niemasd/GameDB-GC/assets/394085/147cf8a7-4c94-434d-9734-bfe47a6e74ee)

**Comment by niemasd** [comment]
@reneruiz Woops, I'm so sorry I missed this! I didn't get a notification, and I never noticed. Yes, I'll close it from here, and can you post it on the MemCard Pro Renamer repo? I'll take a look ASAP! I don't actually have a MemCard Pro, so I wasn't able to test it on GameCube. But should be a quick fix 😄

**Comment by reneruiz** [comment]
Sure thing: https://github.com/niemasd/MemCard-PRO-Renamer/issues/1

**Comment by niemasd** [comment]
Awesome, thank you! And sorry again!
